### ISSUE TITLE
mjai-shanten をクライアントとして動作させる

### ISSUE THREAD

**Issue by shinyaishida** [shinyaishida/mjai#1]
- mjai サーバーから独立したプロセスとして実行される
- 接続先は localhost:11600 でよい
- Ruby でやる

**Comment by shinyaishida** [comment]
mjson のフォーマットを理解したい

**Comment by shinyaishida** [comment]
とりあえずリポジトリの中身をざーっと眺めてみる

**Comment by shinyaishida** [comment]
```
mjai% tree                                                                                                                                                                             [master]
.
├── Gemfile
├── README.rdoc
├── Vagrantfile
├── bin
│   ├── mjai
│   ├── mjai-shanten
│   └── mjai-tsumogiri
├── data
│   ├── shanten_benchmark_data.num.txt
│   └── shanten_benchmark_data.str.txt
├── doc
│   ├── rationale.txt
│   └── todo.txt
├── lib
│   └── mjai
│       ├── action.rb
│       ├── active_game.rb
│       ├── archive.rb
│       ├── archive_player.rb
│       ├── confidence_interval.rb
│       ├── context.rb
│       ├── file_converter.rb
│       ├── furo.rb
│       ├── game.rb
│       ├── game_stats.rb
│       ├── hora.rb
│       ├── jsonizable.rb
│       ├── mentsu.rb
│       ├── mjai_command.rb
│       ├── mjson_archive.rb
│       ├── pai.rb
│       ├── player.rb
│       ├── puppet_player.rb
│       ├── shanten_analysis.rb
│       ├── shanten_player.rb
│       ├── tcp_active_game_server.rb
│       ├── tcp_client_game.rb
│       ├── tcp_game_server.rb
│       ├── tcp_player.rb
│       ├── tenhou_archive.rb
│       ├── tenpai_analysis.rb
│       ├── tsumogiri_player.rb
│       ├── validation_error.rb
│       ├── with_fields.rb
│       └── ymatsux_shanten_analysis.rb
├── log
│   └── log
│       ├── 2021-04-03-111056.mjson
│       ├── 2021-04-03-111349.mjson
│       ├── 2021-04-03-111349.mjson.html
│       └── 2021-04-03-111349.mjson.html.files
│           ├── css
│           │   └── style.css
│           └── js
│               ├── archive_player.js
│               ├── dytem.js
│               └── jquery-1.7.2.min.js
├── mjai-0.0.7.gem
├── mjai.gemspec
├── samples
│   └── tsumogiri_player.rb
├── script
│   └── mjai_server.sh
├── share
│   └── html
│       ├── css
│       │   └── style.scss
│       ├── images
│       │   ├── README.txt
│       │   ├── b_1_1.gif
│       │   ├── b_1_2.gif
│       │   ├── b_5_1.gif
│       │   ├── b_5_2.gif
│       │   ├── b_8_1.gif
│       │   ├── b_8_2.gif
│       │   ├── b_9_1.gif
│       │   ├── b_9_2.gif
│       │   ├── blank.png
│       │   ├── c_c_1.gif
│       │   ├── c_c_2.gif
│       │   ├── c_c_3.gif
│       │   ├── c_c_4.gif
│       │   ├── c_e_1.gif
│       │   ├── c_e_2.gif
│       │   ├── c_e_3.gif
│       │   ├── c_e_4.gif
│       │   ├── c_n_1.gif
│       │   ├── c_n_2.gif
│       │   ├── c_n_3.gif
│       │   ├── c_n_4.gif
│       │   ├── c_s_1.gif
│       │   ├── c_s_2.gif
│       │   ├── c_s_3.gif
│       │   ├── c_s_4.gif
│       │   ├── c_w_1.gif
│       │   ├── c_w_2.gif
│       │   ├── c_w_3.gif
│       │   ├── c_w_4.gif
│       │   ├── dice.gif
│       │   ├── p_bk_0.gif
│       │   ├── p_bk_1.gif
│       │   ├── p_bk_2.gif
│       │   ├── p_bk_3.gif
│       │   ├── p_bk_4.gif
│       │   ├── p_bk_5.gif
│       │   ├── p_bk_6.gif
│       │   ├── p_bk_7.gif
│       │   ├── p_ji_c_0.gif
│       │   ├── p_ji_c_1.gif
│       │   ├── p_ji_c_2.gif
│       │   ├── p_ji_c_3.gif
│       │   ├── p_ji_c_4.gif
│       │   ├── p_ji_c_5.gif
│       │   ├── p_ji_c_6.gif
│       │   ├── p_ji_c_7.gif
│       │   ├── p_ji_e_0.gif
│       │   ├── p_ji_e_1.gif
│       │   ├── p_ji_e_2.gif
│       │   ├── p_ji_e_3.gif
│       │   ├── p_ji_e_4.gif
│       │   ├── p_ji_e_5.gif
│       │   ├── p_ji_e_6.gif
│       │   ├── p_ji_e_7.gif
│       │   ├── p_ji_h_0.gif
│       │   ├── p_ji_h_1.gif
│       │   ├── p_ji_h_2.gif
│       │   ├── p_ji_h_3.gif
│       │   ├── p_ji_h_4.gif
│       │   ├── p_ji_h_5.gif
│       │   ├── p_ji_h_6.gif
│       │   ├── p_ji_h_7.gif
│       │   ├── p_ji_n_0.gif
│       │   ├── p_ji_n_1.gif
│       │   ├── p_ji_n_2.gif
│       │   ├── p_ji_n_3.gif
│       │   ├── p_ji_n_4.gif
│       │   ├── p_ji_n_5.gif
│       │   ├── p_ji_n_6.gif
│       │   ├── p_ji_n_7.gif
│       │   ├── p_ji_s_0.gif
│       │   ├── p_ji_s_1.gif
│       │   ├── p_ji_s_2.gif
│       │   ├── p_ji_s_3.gif
│       │   ├── p_ji_s_4.gif
│       │   ├── p_ji_s_5.gif
│       │   ├── p_ji_s_6.gif
│       │   ├── p_ji_s_7.gif
│       │   ├── p_ji_w_0.gif
│       │   ├── p_ji_w_1.gif
│       │   ├── p_ji_w_2.gif
│       │   ├── p_ji_w_3.gif
│       │   ├── p_ji_w_4.gif
│       │   ├── p_ji_w_5.gif
│       │   ├── p_ji_w_6.gif
│       │   ├── p_ji_w_7.gif
│       │   ├── p_ms1_0.gif
│       │   ├── p_ms1_1.gif
│       │   ├── p_ms1_2.gif
│       │   ├── p_ms1_3.gif
│       │   ├── p_ms1_4.gif
│       │   ├── p_ms1_5.gif
│       │   ├── p_ms1_6.gif
│       │   ├── p_ms1_7.gif
│       │   ├── p_ms2_0.gif
│       │   ├── p_ms2_1.gif
│       │   ├── p_ms2_2.gif
│       │   ├── p_ms2_3.gif
│       │   ├── p_ms2_4.gif
│       │   ├── p_ms2_5.gif
│       │   ├── p_ms2_6.gif
│       │   ├── p_ms2_7.gif
│       │   ├── p_ms3_0.gif
│       │   ├── p_ms3_1.gif
│       │   ├── p_ms3_2.gif
│       │   ├── p_ms3_3.gif
│       │   ├── p_ms3_4.gif
│       │   ├── p_ms3_5.gif
│       │   ├── p_ms3_6.gif
│       │   ├── p_ms3_7.gif
│       │   ├── p_ms4_0.gif
│       │   ├── p_ms4_1.gif
│       │   ├── p_ms4_2.gif
│       │   ├── p_ms4_3.gif
│       │   ├── p_ms4_4.gif
│       │   ├── p_ms4_5.gif
│       │   ├── p_ms4_6.gif
│       │   ├── p_ms4_7.gif
│       │   ├── p_ms5_0.gif
│       │   ├── p_ms5_1.gif
│       │   ├── p_ms5_2.gif
│       │   ├── p_ms5_3.gif
│       │   ├── p_ms5_4.gif
│       │   ├── p_ms5_5.gif
│       │   ├── p_ms5_6.gif
│       │   ├── p_ms5_7.gif
│       │   ├── p_ms5r_1.png
│       │   ├── p_ms5r_3.png
│       │   ├── p_ms6_0.gif
│       │   ├── p_ms6_1.gif
│       │   ├── p_ms6_2.gif
│       │   ├── p_ms6_3.gif
│       │   ├── p_ms6_4.gif
│       │   ├── p_ms6_5.gif
│       │   ├── p_ms6_6.gif
│       │   ├── p_ms6_7.gif
│       │   ├── p_ms7_0.gif
│       │   ├── p_ms7_1.gif
│       │   ├── p_ms7_2.gif
│       │   ├── p_ms7_3.gif
│       │   ├── p_ms7_4.gif
│       │   ├── p_ms7_5.gif
│       │   ├── p_ms7_6.gif
│       │   ├── p_ms7_7.gif
│       │   ├── p_ms8_0.gif
│       │   ├── p_ms8_1.gif
│       │   ├── p_ms8_2.gif
│       │   ├── p_ms8_3.gif
│       │   ├── p_ms8_4.gif
│       │   ├── p_ms8_5.gif
│       │   ├── p_ms8_6.gif
│       │   ├── p_ms8_7.gif
│       │   ├── p_ms9_0.gif
│       │   ├── p_ms9_1.gif
│       │   ├── p_ms9_2.gif
│       │   ├── p_ms9_3.gif
│       │   ├── p_ms9_4.gif
│       │   ├── p_ms9_5.gif
│       │   ├── p_ms9_6.gif
│       │   ├── p_ms9_7.gif
│       │   ├── p_no_0.gif
│       │   ├── p_no_1.gif
│       │   ├── p_no_2.gif
│       │   ├── p_no_3.gif
│       │   ├── p_no_4.gif
│       │   ├── p_no_5.gif
│       │   ├── p_no_6.gif
│       │   ├── p_no_7.gif
│       │   ├── p_ps1_0.gif
│       │   ├── p_ps1_1.gif
│       │   ├── p_ps1_2.gif
│       │   ├── p_ps1_3.gif
│       │   ├── p_ps1_4.gif
│       │   ├── p_ps1_5.gif
│       │   ├── p_ps1_6.gif
│       │   ├── p_ps1_7.gif
│       │   ├── p_ps2_0.gif
│       │   ├── p_ps2_1.gif
│       │   ├── p_ps2_2.gif
│       │   ├── p_ps2_3.gif
│       │   ├── p_ps2_4.gif
│       │   ├── p_ps2_5.gif
│       │   ├── p_ps2_6.gif
│       │   ├── p_ps2_7.gif
│       │   ├── p_ps3_0.gif
│       │   ├── p_ps3_1.gif
│       │   ├── p_ps3_2.gif
│       │   ├── p_ps3_3.gif
│       │   ├── p_ps3_4.gif
│       │   ├── p_ps3_5.gif
│       │   ├── p_ps3_6.gif
│       │   ├── p_ps3_7.gif
│       │   ├── p_ps4_0.gif
│       │   ├── p_ps4_1.gif
│       │   ├── p_ps4_2.gif
│       │   ├── p_ps4_3.gif
│       │   ├── p_ps4_4.gif
│       │   ├── p_ps4_5.gif
│       │   ├── p_ps4_6.gif
│       │   ├── p_ps4_7.gif
│       │   ├── p_ps5_0.gif
│       │   ├── p_ps5_1.gif
│       │   ├── p_ps5_2.gif
│       │   ├── p_ps5_3.gif
│       │   ├── p_ps5_4.gif
│       │   ├── p_ps5_5.gif
│       │   ├── p_ps5_6.gif
│       │   ├── p_ps5_7.gif
│       │   ├── p_ps5r_1.png
│       │   ├── p_ps5r_3.png
│       │   ├── p_ps6_0.gif
│       │   ├── p_ps6_1.gif
│       │   ├── p_ps6_2.gif
│       │   ├── p_ps6_3.gif
│       │   ├── p_ps6_4.gif
│       │   ├── p_ps6_5.gif
│       │   ├── p_ps6_6.gif
│       │   ├── p_ps6_7.gif
│       │   ├── p_ps7_0.gif
│       │   ├── p_ps7_1.gif
│       │   ├── p_ps7_2.gif
│       │   ├── p_ps7_3.gif
│       │   ├── p_ps7_4.gif
│       │   ├── p_ps7_5.gif
│       │   ├── p_ps7_6.gif
│       │   ├── p_ps7_7.gif
│       │   ├── p_ps8_0.gif
│       │   ├── p_ps8_1.gif
│       │   ├── p_ps8_2.gif
│       │   ├── p_ps8_3.gif
│       │   ├── p_ps8_4.gif
│       │   ├── p_ps8_5.gif
│       │   ├── p_ps8_6.gif
│       │   ├── p_ps8_7.gif
│       │   ├── p_ps9_0.gif
│       │   ├── p_ps9_1.gif
│       │   ├── p_ps9_2.gif
│       │   ├── p_ps9_3.gif
│       │   ├── p_ps9_4.gif
│       │   ├── p_ps9_5.gif
│       │   ├── p_ps9_6.gif
│       │   ├── p_ps9_7.gif
│       │   ├── p_ss1_0.gif
│       │   ├── p_ss1_1.gif
│       │   ├── p_ss1_2.gif
│       │   ├── p_ss1_3.gif
│       │   ├── p_ss1_4.gif
│       │   ├── p_ss1_5.gif
│       │   ├── p_ss1_6.gif
│       │   ├── p_ss1_7.gif
│       │   ├── p_ss2_0.gif
│       │   ├── p_ss2_1.gif
│       │   ├── p_ss2_2.gif
│       │   ├── p_ss2_3.gif
│       │   ├── p_ss2_4.gif
│       │   ├── p_ss2_5.gif
│       │   ├── p_ss2_6.gif
│       │   ├── p_ss2_7.gif
│       │   ├── p_ss3_0.gif
│       │   ├── p_ss3_1.gif
│       │   ├── p_ss3_2.gif
│       │   ├── p_ss3_3.gif
│       │   ├── p_ss3_4.gif
│       │   ├── p_ss3_5.gif
│       │   ├── p_ss3_6.gif
│       │   ├── p_ss3_7.gif
│       │   ├── p_ss4_0.gif
│       │   ├── p_ss4_1.gif
│       │   ├── p_ss4_2.gif
│       │   ├── p_ss4_3.gif
│       │   ├── p_ss4_4.gif
│       │   ├── p_ss4_5.gif
│       │   ├── p_ss4_6.gif
│       │   ├── p_ss4_7.gif
│       │   ├── p_ss5_0.gif
│       │   ├── p_ss5_1.gif
│       │   ├── p_ss5_2.gif
│       │   ├── p_ss5_3.gif
│       │   ├── p_ss5_4.gif
│       │   ├── p_ss5_5.gif
│       │   ├── p_ss5_6.gif
│       │   ├── p_ss5_7.gif
│       │   ├── p_ss5r_1.png
│       │   ├── p_ss5r_3.png
│       │   ├── p_ss6_0.gif
│       │   ├── p_ss6_1.gif
│       │   ├── p_ss6_2.gif
│       │   ├── p_ss6_3.gif
│       │   ├── p_ss6_4.gif
│       │   ├── p_ss6_5.gif
│       │   ├── p_ss6_6.gif
│       │   ├── p_ss6_7.gif
│       │   ├── p_ss7_0.gif
│       │   ├── p_ss7_1.gif
│       │   ├── p_ss7_2.gif
│       │   ├── p_ss7_3.gif
│       │   ├── p_ss7_4.gif
│       │   ├── p_ss7_5.gif
│       │   ├── p_ss7_6.gif
│       │   ├── p_ss7_7.gif
│       │   ├── p_ss8_0.gif
│       │   ├── p_ss8_1.gif
│       │   ├── p_ss8_2.gif
│       │   ├── p_ss8_3.gif
│       │   ├── p_ss8_4.gif
│       │   ├── p_ss8_5.gif
│       │   ├── p_ss8_6.gif
│       │   ├── p_ss8_7.gif
│       │   ├── p_ss9_0.gif
│       │   ├── p_ss9_1.gif
│       │   ├── p_ss9_2.gif
│       │   ├── p_ss9_3.gif
│       │   ├── p_ss9_4.gif
│       │   ├── p_ss9_5.gif
│       │   ├── p_ss9_6.gif
│       │   └── p_ss9_7.gif
│       ├── js
│       │   ├── archive_player.coffee
│       │   ├── archive_player.js
│       │   ├── dytem.coffee
│       │   ├── dytem.js
│       │   └── jquery-1.7.2.min.js
│       └── views
│           └── archive_player.erb
├── ssh.config
├── test
│   ├── kuikae.mjson
│   ├── kuikae_only.mjson
│   ├── test.mjlog
│   ├── test.mjlog.golden.log
│   ├── test_hora.rb
│   ├── test_pai.rb
│   ├── test_shanten_analysis.rb
│   ├── test_tenhou_archive.rb
│   ├── test_tenhou_archive_regression.rb
│   ├── test_tenpai_analysis.rb
│   └── test_ymatsux_shanten_analysis.rb
└── tools
    └── benchmark_shanten_analysis.rb

20 directories, 388 files
```

**Comment by shinyaishida** [comment]
```
├── samples
│   └── tsumogiri_player.rb
```
を見てみる

**Comment by shinyaishida** [comment]
Vagrant でサーバーを立ち上げて、そこに samples/tsumogiri_player.rb で繋いでみる。Vagrant では 3 プレイヤーで待ち状態にする。
```
vagrant@vagrant-ubuntu-trusty-64:~$ mjai server --port=11600 --game_type=one_kyoku --room=default --log_dir=./log mjai-shanten mjai-shanten mjai-shanten
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.
Listening on host 127.0.0.1, port 11600
URL: mjsonp://localhost:11600/default
Waiting for 4 players...
mjai-shanten mjsonp://localhost:11600/default
mjai-shanten mjsonp://localhost:11600/default
mjai-shanten mjsonp://localhost:11600/default
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.

NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.
server -> player ?	{"type":"hello","protocol":"mjsonp","protocol_version":3}
<-	{"type":"hello","protocol":"mjsonp","protocol_version":3}
->	{"type":"join","name":"shanten","room":"default"}
server <- player ?	{"type":"join","name":"shanten","room":"default"}
Waiting for 3 more players...
server -> player ?	{"type":"hello","protocol":"mjsonp","protocol_version":3}
<-	{"type":"hello","protocol":"mjsonp","protocol_version":3}
->	{"type":"join","name":"shanten","room":"default"}
server <- player ?	{"type":"join","name":"shanten","room":"default"}
Waiting for 2 more players...
server -> player ?	{"type":"hello","protocol":"mjsonp","protocol_version":3}
<-	{"type":"hello","protocol":"mjsonp","protocol_version":3}
->	{"type":"join","name":"shanten","room":"default"}
server <- player ?	{"type":"join","name":"shanten","room":"default"}
Waiting for 1 more players...
```

**Comment by shinyaishida** [comment]
```
mjai% samples/tsumogiri_player.rb 127.0.0.1:11600
Traceback (most recent call last):
	3: from samples/tsumogiri_player.rb:8:in `<main>'
	2: from /Users/shinyaishida/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
	1: from /Users/shinyaishida/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
/Users/shinyaishida/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "127.0.0.1:11600" (URI::InvalidURIError)
```

**Comment by shinyaishida** [comment]
おとさたなし。
```
mjai% samples/tsumogiri_player.rb http://127.0.0.1:11600
mjai%
```

**Comment by shinyaishida** [comment]
仮想マシンの中でやってみる

**Comment by shinyaishida** [comment]
スクリプトが見つからん

**Comment by shinyaishida** [comment]
```
vagrant@vagrant-ubuntu-trusty-64:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:5f:bb:e6 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe5f:bbe6/64 scope link
       valid_lft forever preferred_lft forever
vagrant@vagrant-ubuntu-trusty-64:~$ netstat -ln | grep 11600
tcp        0      0 127.0.0.1:11600         0.0.0.0:*               LISTEN
```

**Comment by shinyaishida** [comment]
ホスト側から 10.0.2.15:11600 に繋げてみる

**Comment by shinyaishida** [comment]
```
mjai% samples/tsumogiri_player.rb http://10.0.2.15:11600
^CTraceback (most recent call last):
	2: from samples/tsumogiri_player.rb:9:in `<main>'
	1: from samples/tsumogiri_player.rb:9:in `new'
samples/tsumogiri_player.rb:9:in `initialize': Interrupt
```

**Comment by shinyaishida** [comment]
initialize で止まってるみたい

**Comment by shinyaishida** [comment]
TCPコネクションを確立できてないのかな

**Comment by shinyaishida** [comment]
仮想マシン内から telnet やると繋がる
```
vagrant@vagrant-ubuntu-trusty-64:~$ telnet localhost 11600
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"type":"hello","protocol":"mjsonp","protocol_version":3}
```

**Comment by shinyaishida** [comment]
mjsonp というプロトコル、バージョンは3

**Comment by shinyaishida** [comment]
てきとーに hello を返したら接続切られた。。
```
{"type":"hello","protocol":"mjsonp","protocol_version":3}
{"type":"error","message":"Expected e.g. {\"type\":\"join\",\"name\":\"noname\",\"room\":\"default\"}"}
Connection closed by foreign host.
```

**Comment by shinyaishida** [comment]
tumogiri_player.rb に渡す引数の URI のパスで room を指定しないといけなかった。
```ruby
    when "hello"
      response = {
          "type" => "join",
          "name" => "tsumogiri",
          "room" => uri.path[1..-1],
      }
```

**Comment by shinyaishida** [comment]
サーバーの起動ログから room は default

**Comment by shinyaishida** [comment]
うまくいかない
```
mjai% samples/tsumogiri_player.rb http://10.0.2.15:11600/default/
^C^CTraceback (most recent call last):
	2: from samples/tsumogiri_player.rb:9:in `<main>'
	1: from samples/tsumogiri_player.rb:9:in `new'
samples/tsumogiri_player.rb:9:in `initialize': Interrupt
```

**Comment by shinyaishida** [comment]
ruby のバージョンを Vagrant のやつと同じにする
```
vagrant@vagrant-ubuntu-trusty-64:~$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

**Comment by shinyaishida** [comment]
```
mjai% rbenv install 1.9.3-p484
```

**Comment by shinyaishida** [comment]
あれ、仮想マシン内の /usr/local/bin の mjai-tsumogiri でいいんじゃ。。
```
vagrant@vagrant-ubuntu-trusty-64:~$ ls /usr/local/bin/
bundle  mjai  mjai-shanten  mjai-tsumogiri  nokogiri  sass  sass-convert
```

**Comment by shinyaishida** [comment]
割と親切
```
$ mjai-tsumogiri
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.
Usage:
  /usr/local/bin/mjai-tsumogiri mjsonp://localhost:11600/default
```

**Comment by shinyaishida** [comment]
```
$ mjai-tsumogiri mjsonp://localhost:11600/default
```
で繋がった。つもぎってる。

**Comment by shinyaishida** [comment]
対局が終わると待ちに戻る
```
--------------------------------------------------------------------------------
server -> player 0	{"type":"end_game","scores":[24000,24000,24000,28000]}
<-	{"type":"end_game","scores":[24000,24000,24000,28000]}
server :  Player 0 has disconnected.
server -> player 1	{"type":"end_game","scores":[24000,24000,24000,28000]}
<-	{"type":"end_game","scores":[24000,24000,24000,28000]}
server :  Player 1 has disconnected.
server -> player 2	{"type":"end_game","scores":[24000,24000,24000,28000]}
server :  Player 2 has disconnected.
server -> player 3	{"type":"end_game","scores":[24000,24000,24000,28000]}
<-	{"type":"end_game","scores":[24000,24000,24000,28000]}
server :  Player 3 has disconnected.
game 2: shanten:28000 shanten:24000 shanten:24000 tsumogiri:24000
Average rank: shanten:2.167 [1.375, 3.125] tsumogiri:3.500 [1.750, 4.000]
Average score: shanten:25166 tsumogiri:24500
mjai-shanten mjsonp://localhost:11600/default
mjai-shanten mjsonp://localhost:11600/default
mjai-shanten mjsonp://localhost:11600/default
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.

NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/lib/gems/1.9.1/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3.
server -> player ?	{"type":"hello","protocol":"mjsonp","protocol_version":3}server -> player ?	{"type":"hello","protocol":"mjsonp","protocol_version":3}

<-	{"type":"hello","protocol":"mjsonp","protocol_version":3}
->	{"type":"join","name":"shanten","room":"default"}
server <- player ?	{"type":"join","name":"shanten","room":"default"}
Waiting for 3 more players...<-	{"type":"hello","protocol":"mjsonp","protocol_version":3}
->	{"type":"join","name":"shanten","room":"default"}

server <- player ?	{"type":"join","name":"shanten","room":"default"}
Waiting for 2 more players...
server -> player ?	{"type":"hello","protocol":"mjsonp","protocol_version":3}
<-	{"type":"hello","protocol":"mjsonp","protocol_version":3}
->	{"type":"join","name":"shanten","room":"default"}
server <- player ?	{"type":"join","name":"shanten","room":"default"}
Waiting for 1 more players...
```

**Comment by shinyaishida** [comment]
mjai-tsumogiri を mjai-shanten にしても動く
